# Install script for directory: /work/opencv

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "dlpack-LICENSE" FILES "/work/opencv/3rdparty/dlpack/LICENSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-readme.htm" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/icv/readme.htm")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-EULA.txt" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/EULA.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippicv-third-party-programs.txt" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/third-party-programs.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-support.txt" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/icv/../iw/../support.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-third-party-programs.txt" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/icv/../iw/../third-party-programs.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ippiw-EULA.txt" FILES "/work/opencv/build-sample/3rdparty/ippicv/ippicv_lnx/icv/../iw/../EULA.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "flatbuffers-LICENSE.txt" FILES "/work/opencv/3rdparty/flatbuffers/LICENSE.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "opencl-headers-LICENSE.txt" FILES "/work/opencv/3rdparty/include/opencl/LICENSE.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ade-LICENSE" FILES "/work/opencv/build-sample/3rdparty/ade/ade-0.1.2e/LICENSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/work/opencv/build-sample/cvconfig.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/work/opencv/build-sample/opencv2/opencv_modules.hpp")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake")
    file(DIFFERENT _cmake_export_file_changed FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake"
         "/work/opencv/build-sample/CMakeFiles/Export/51ea738ee2ea68756d9122094dacc2a4/OpenCVModules.cmake")
    if(_cmake_export_file_changed)
      file(GLOB _cmake_old_config_files "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules-*.cmake")
      if(_cmake_old_config_files)
        string(REPLACE ";" ", " _cmake_old_config_files_text "${_cmake_old_config_files}")
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake\" will be replaced.  Removing files [${_cmake_old_config_files_text}].")
        unset(_cmake_old_config_files_text)
        file(REMOVE ${_cmake_old_config_files})
      endif()
      unset(_cmake_old_config_files)
    endif()
    unset(_cmake_export_file_changed)
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/work/opencv/build-sample/CMakeFiles/Export/51ea738ee2ea68756d9122094dacc2a4/OpenCVModules.cmake")
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/work/opencv/build-sample/CMakeFiles/Export/51ea738ee2ea68756d9122094dacc2a4/OpenCVModules-relwithdebinfo.cmake")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES
    "/work/opencv/build-sample/unix-install/OpenCVConfig-version.cmake"
    "/work/opencv/build-sample/unix-install/OpenCVConfig.cmake"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "scripts" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "/work/opencv/build-sample/CMakeFiles/install/setup_vars_opencv4.sh")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/opencv4" TYPE FILE FILES
    "/work/opencv/platforms/scripts/valgrind.supp"
    "/work/opencv/platforms/scripts/valgrind_3rdparty.supp"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/work/opencv/build-sample/3rdparty/libwebp/cmake_install.cmake")
  include("/work/opencv/build-sample/3rdparty/openjpeg/cmake_install.cmake")
  include("/work/opencv/build-sample/3rdparty/ippiw/cmake_install.cmake")
  include("/work/opencv/build-sample/3rdparty/protobuf/cmake_install.cmake")
  include("/work/opencv/build-sample/hal/ipp/cmake_install.cmake")
  include("/work/opencv/build-sample/3rdparty/ittnotify/cmake_install.cmake")
  include("/work/opencv/build-sample/include/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/core/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/dnn/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/features2d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/flann/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/gapi/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/highgui/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/java/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/js/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/ml/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/objc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/photo/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/python/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/stitching/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/ts/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/video/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/videoio/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/world/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/alphamat/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/aruco/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cannops/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/ccalib/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cudev/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/cvv/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/datasets/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/dpm/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/face/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/fastcv/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/freetype/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/hdf/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/hfs/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/img_hash/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/intensity_transform/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/julia/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/matlab/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/mcc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/optflow/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/ovis/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/plot/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/quality/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/rapid/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/reg/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/rgbd/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/saliency/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/sfm/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/shape/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/signal/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/stereo/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/structured_light/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/superres/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/text/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/tracking/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/videostab/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/viz/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/wechat_qrcode/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/.firstpass/xphoto/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/core/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/flann/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/imgproc/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/features2d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/imgcodecs/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/calib3d/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/objdetect/cmake_install.cmake")
  include("/work/opencv/build-sample/modules/aruco/cmake_install.cmake")
  include("/work/opencv/build-sample/doc/cmake_install.cmake")
  include("/work/opencv/build-sample/data/cmake_install.cmake")
  include("/work/opencv/build-sample/apps/cmake_install.cmake")
  include("/work/opencv/build-sample/samples/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/work/opencv/build-sample/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/work/opencv/build-sample/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
