# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS opencv_core opencv_flann opencv_imgproc opencv_features2d opencv_imgcodecs opencv_calib3d opencv_objdetect opencv_aruco)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

set_target_properties(opencv_flann PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_core"
)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

set_target_properties(opencv_imgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_core"
)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

set_target_properties(opencv_features2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_core;opencv_flann;opencv_imgproc"
)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

set_target_properties(opencv_imgcodecs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_core;opencv_imgproc"
)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

set_target_properties(opencv_calib3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d"
)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

set_target_properties(opencv_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_aruco
add_library(opencv_aruco SHARED IMPORTED)

set_target_properties(opencv_aruco PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_objdetect;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_objdetect"
)

# Import target "opencv_core" for configuration "RelWithDebInfo"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_core.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_core.so.413"
  )

# Import target "opencv_flann" for configuration "RelWithDebInfo"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_flann.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_flann.so.413"
  )

# Import target "opencv_imgproc" for configuration "RelWithDebInfo"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_imgproc.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_imgproc.so.413"
  )

# Import target "opencv_features2d" for configuration "RelWithDebInfo"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_features2d.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_features2d.so.413"
  )

# Import target "opencv_imgcodecs" for configuration "RelWithDebInfo"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_imgcodecs.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_imgcodecs.so.413"
  )

# Import target "opencv_calib3d" for configuration "RelWithDebInfo"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_calib3d.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_calib3d.so.413"
  )

# Import target "opencv_objdetect" for configuration "RelWithDebInfo"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_objdetect.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_objdetect.so.413"
  )

# Import target "opencv_aruco" for configuration "RelWithDebInfo"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/work/opencv/build-sample/lib/libopencv_aruco.so.4.13.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopencv_aruco.so.413"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
